<?php

// function commerce_razorpay_checkout_form() {
// // Add meta tag.
// drupal_add_html_head('<meta name="viewport" content="width=device-width”>');
// $form['test'] = array(
//     '#type' => 'markup',
//     '#markup' => '<button id="rzp-button1">Pay</button>');
// // drupal_add_js(drupal_get_path('module', 'commerce_razorpay') . '/commerce_razorpay.js');
// // drupal_add_js('https://checkout.razorpay.com/v1/checkout.js');
// $order = create_an_order();


// $path1 = drupal_get_path('module', 'commerce_razorpay') . '/custom1.js';
// $path1 = 'https://checkout.razorpay.com/v1/checkout.js';


// $form['#attached']['js'][] = "https://checkout.razorpay.com/v1/checkout.js";

// drupal_add_js(array('commerce_razorpay' => array('amount' => 100, 'key' => 'rzp_test_6VOiSPZ8ClqeCo', 'logo' => drupal_get_path('module', 'commerce_razorpay') .'/logo.jpg', 'order_id' => $order->id)), array('type' => 'setting'));

// $form['#attached']['js'][] = drupal_get_path('module', 'commerce_razorpay')."/commerce_razorpay.js";

// return $form;
// }
